services:
  ros2_galactic:
    image: osrf/ros:galactic-desktop
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
    volumes:
      - .:/home
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyACM1:/dev/ttyACM1
    command: >
      bash -c "cd /home
      && touch test.txt
      "
      
    
    
    
    
