services:
  ros2_galactic:
    container_name: ros2_galactic
    image: VEX-ROS2-USER/custom_docker:local_image
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
    #privileged: true
    ports:
      - name: "ros2_galactic_comm"
        protocol: "tcp"
        target: 6969
        published: "6969"
        mode: ingress
    volumes:
      # VEX ROS2 volumes
      - ./vex_brain:/home/VEX-ROS/vex_brain
      - ./vex_message:/home/VEX-ROS/vex_message
      - ./vex_log:/home/VEX-ROS/vex_log
      - ./model:/home/VEX-ROS/model
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyACM1:/dev/ttyACM1
    command: >
      bash -c "cd /home/VEX-ROS
      && ./entrypoint.sh ${MODE}
      "
