services:
  ros2_galactic:
    container_name: ros2_galactic
    image: VEX-ROS2-USER/custom_docker:local_image
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
    #privileged: true
    environment:
      - VEX_CONNECTED=${VEX_CONNECTED}
    ports:
      - name: "ros2_galactic_comm"
        protocol: "tcp"
        target: 6969
        published: "6969"
        mode: ingress
    volumes:
      # VEX ROS2 volumes
      - ./vex_brain:/home/VEX-ROS/vex_brain
      - ./vex_message:/home/VEX-ROS/vex_message
      - ./vex_log:/home/VEX-ROS/vex_log
      - ./model:/home/VEX-ROS/model
    devices:
      - ${VEX_COM_PORT:-/dev/null}:/dev/ttyACM0
      - ${VEX_USER_PORT:-/dev/null}:/dev/ttyACM1
    command: >
      bash -c "cd /home/VEX-ROS
      && ./entrypoint.sh ${MODE}
      "